name: "build"
on: 
  push:
        
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install cookiecutter 
        run: |
          pip install cookiecutter
      - name: Test cookiecutter
        run: |
          mkdir -p project/download 
          cookiecutter . --no-input
      - name : Create zip
        uses: papeloto/action-zip@v1
        with:
          files: project/download/
          dest: result.zip
